const RP_NAME = "Stellar Wallet";
const RP_ID = "stellar-wallet.com";
const ACCOUNT_URL = "https://friendbot.stellar.org?addr=";
const SOROBAN_CONTRACT_ID = "CAWTECLBR7PXGY7EEYQ4NRCDEMJHOZMGIERBE5I23ZZBLOCBZRIDGYEL";
const SOROBAN_SERVER_ADDRESS = "https://soroban-testnet.stellar.org";
const PUBLIC = "GBEURBN6SAQRKUDSVWS2CWEZZYOCX2OWFTNWJ7QBYGHFGAJQ6TEU27NO";
const PRIVATE = "SD3Q4ABIVQ2IVBHSLKIAZPIWTQBK6FLRYNPDMZEZZINKVOL2PDBGIEVB";
